### ISSUE TITLE
Mod 0 Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [evanmarkowitz/mod_0_skills#1]
# Checklist/Rubric

#### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub
* [x]  Directories are named correctly.
* [x]  Files are named correctly.
* [x]  Files and directories are structured correctly.
* [x]  Initial commit was made.
* [x]  Initial commit was pushed to GitHub.

#### Part II: Top Down Design
* [x]  Larger processes were broken into smaller layers.
* [x]  Changes were added and committed with a properly formatted commit message starting with a verb and a capital letter.
* [x]  Changes were pushed to Github.

#### Part III: Classes in a System
* [x]  Directories and files were named and structured correctly.
* [x]  The attributes chosen for **Class #1** represent states or characteristics.
* [ ]  The attributes chosen for **Class #2** represent states or characteristics.
* [x]  The attributes chosen for **Class #3** represent states or characteristics.
* [x]  The methods chosen for **Class #1** represent behaviors or actions.
* [x]  The methods chosen for **Class #2** represent behaviors or actions.
* [x]  The methods chosen for **Class #3** represent behaviors or actions.
* [x]  Data type (string, integer, boolean, array, hash/object, datetime) were identified for each attribute in all three classes.
* [ ]  Individual changes were added and committed separately with a properly formatted commit message.
* [x]  Changes were pushed to Github.

**Mod 0 Technical Assessment Results**

* [ ]   Technical Ready
* [x]   Pending
* [ ]   Not Ready

**Comment by timomitchel** [comment]
Good job on the assessment @evanmarkowitz. I just want you to make a few changes to this and you will then be deemed ```Technical Ready```. For a class, the class should be named in a singular manner instead of a plural one. It looks like you named 4/5 commits `Initial Commit`. Go ahead and make the singular changes to your class files and commit each change **separately** with a properly formatted commit messages. I also want to point out a few things about your attributes. In the first class file, `Hours` would be represented as a `Range`. That's not a data-type we went over, so don't worry about not knowing that. I just wanted to let you know. For class 2 `Average Order Value` and `Number of Reviews` definitely feel like attributes at first, but they would be methods because they would both be returning a value that would constantly be changing based on other inputs. The data types are correct, but in our organization of the class we would have those listed as methods. Class 3 looks great. Go ahead and make the above changes to the repo, and DM Rachel and I when you have them complete. Thanks!
